# -*- coding: utf-8 -*-
"""OBJECT DETECTION SINGLE IMAGE.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1948LlAziNJRp2quTV7MUlW4UhgFg2S-H
"""

# Install required libraries
!pip install ultralytics

import cv2
from google.colab import files
from ultralytics import YOLO
from IPython.display import display, Image

# Upload an image
uploaded = files.upload()
image_path = next(iter(uploaded))

# Load the YOLO model
model = YOLO('yolov8n.pt')  # Load the smallest YOLOv8 model

# Perform object detection
results = model(image_path)

# Get the first result (since we're only processing one image)
result = results[0]

# Read the image
img = cv2.imread(image_path)

# Draw bounding boxes and labels on the image
for box in result.boxes:
    x1, y1, x2, y2 = map(int, box.xyxy[0])
    conf = float(box.conf)
    cls = int(box.cls)
    label = f"{result.names[cls]} {conf:.2f}"

    cv2.rectangle(img, (x1, y1), (x2, y2), (0, 255, 0), 2)
    cv2.putText(img, label, (x1, y1 - 10), cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 255, 0), 2)

# Save the result
cv2.imwrite('result.jpg', img)

# Display the result
display(Image('result.jpg'))

# Print detected objects
for box in result.boxes:
    print(f"Detected: {result.names[int(box.cls)]} confidence {float(box.conf):.2f}")